name: Build Docusaurus doc

on:
  push:
    branches:
      - main
      - docusaurus
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docs
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
      - name: Installation
        run: yarn

      - name: Build docs
        run: yarn build

      - name: Archive the docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build/

  deploy:
    name: Deploy the new doc
    needs: build
    if: github.ref == 'refs/heads/docusaurus'
    runs-on: ubuntu-latest
    steps:
      - name: Download the built docs artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs

      - name: list
        run: ls -lah

      - name: Install tools
        run: |
          sudo apt install sshpass rsync
          mkdir .ssh;             chmod 700 .ssh
          touch .ssh/known_hosts  chmod 600 .ssh/known_hosts
          ssh-keyscan nextdoc.yunohost.org >> .ssh/known_hosts


      - name: Deploy
        run: sshpass -p ${{ secrets.DOC_SFTP_PWD }} rsync -avz --delete docs/ my_webapp@nextdoc.yunohost.org:~/www/
