name: Lint Markdown

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        config: .markdownlint-cli2.yaml
        globs: 'pages'
